backend = "resized"
color_space = "labmixed"
palette = "dark16"
threshold = 11

[templates]
waybar.template = "colors-waybar.css"
waybar.target = "~/.config/waybar/wallust/colors-waybar.css"

rofi.template = "colors-rofi.rasi"
rofi.target = "~/.config/rofi/wallust/colors-rofi.rasi"

swaync.template = "colors-swaync.css"
swaync.target = "~/.config/swaync/wallust/colors-swaync.css"

wlogout.template = "colors-wlogout.css"
wlogout.target = "~/.config/wlogout/wallust-colors.css"
